apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: phpldapadmin
  name: phpldapadmin
  namespace: alauda-system
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    io.kompose.service: phpldapadmin
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: phpldapadmin
  name: phpldapadmin-Nodeport
  namespace: alauda-system
spec:
  ports:
    - name: '8080'
      protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    io.kompose.service: phpldapadmin
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
